[tool.poetry]
name = "coursework2"
version = "0.1.0"
description = "Парсер вакансий с hh.ru"
authors = ["Swetlana Mirzoeva <levka008@mail.ru>"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.9"
requests = ">=2.31.0"

[tool.poetry.group.dev.dependencies]
pytest = ">=7.4.0"
pytest-cov = ">=4.1.0"
types-requests = "^2.32.4.20250809"


[tool.poetry.group.lint.dependencies]
mypy = "^1.17.1"
flake8 = "^7.3.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"